--- #YAML:1.0
name:                AnyEvent-DNS
version:             0.01
abstract:            Helper for non-blocking DNS queries with Net::DNS
license:             perl
author:              
    - Robin Redeker <elmex@ta-sa.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    AnyEvent:                      0
    Net::DNS:                      0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
